---
apiVersion: v1
kind: Service
metadata:
  name: kelechi-redis-service
  labels:
      username: kelechi
      env: test
spec:
  type: ClusterIP
  selector:
    app: kelechi-test-redis
    
  ports:
  - name: kelechi-test-redis
    port: 6379
    targetPort: 6379