---
version: '3'

services:
  redis-db:
    image: redis:7
    ports:
      - "6379:6379"
    command: --save 1 1
    volumes:
      - ./data:/data
    user: "1000:1000"

  flask-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - kelechi-redis-service
    image: kelach/atx_traffic:1.0
    ports:
      - "5000:5000"
    volumes:
      - ./config.yaml:/config.yaml
    environment:
      - REDIS_IP="redis_ip_here"	